[package]
name = "chess"
version = "1.0.1"
edition = "2024"

[dependencies]
ggez = "0.9"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
local-ip-address = "0.5"
arboard = "3.2"
